os: osx
osx_image: xcode14.2
language: objective-c
matrix:
  include:
    - stage: Static Library & Tests
      script:
        - xcodebuild -project InAppSettingsKit.xcodeproj -scheme InAppSettingsKit -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' build | xcpretty
    - stage: Framework
      script:
        - xcodebuild -project InAppSettingsKit.xcodeproj -scheme InAppSettingsKitFramework -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' build | xcpretty
    - stage: Sample App
      script:
        - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme Sample\ App -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' build | xcpretty
    - stage: Carthage Setup
      script:
        - brew update
        - (brew list carthage && brew upgrade carthage) || brew install carthage
        - ./scripts/test-carthage.sh
