os: osx
osx_image: xcode12.2
language: objective-c
xcode_workspace: InAppSettingsKit.xcworkspace
xcode_destination: platform=iOS Simulator,OS=14.1,name=iPhone 12
matrix:
  include:
    - stage: Static Library & Tests
      xcode_scheme: InAppSettingsKit
    - stage: Framework
      script:
        - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme InAppSettingsKitFramework build | xcpretty
    - stage: Sample App
      script:
        - xcodebuild -workspace InAppSettingsKit.xcworkspace -scheme Sample\ App -destination platform\=iOS\ Simulator,OS\=14.1,name\=iPhone\ 12 build | xcpretty
    - stage: Carthage Setup
      script:
        - brew update
        - (brew list carthage && brew upgrade carthage) || brew install carthage
        - ./scripts/test-carthage.sh
